spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://sit-db.example.local:5432/payments
    username: pay_user
    password: ${PAY_DB_PASSWORD:changeme}
app:
  featureFlags:
    newCheckout: false
  kafka:
    bootstrapServers: sit-kafka.example.local:9092
    topicPayments: payments.sit