# Base configuration loaded for all applications and environments
server:
  port: 8080
  servlet:
    context-path: /api
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    info:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
      
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false
    show-sql: false
    
app:
  companyName: "ExampleCorp"
  version: "@project.version@"
  timezone: "UTC"
  cors:
    allowed-origins: "*"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  security:
    jwt:
      expiration: 86400 # 24 hours in seconds
  cache:
    ttl: 300 # 5 minutes in seconds