spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
app:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:4200"
  security:
    jwt:
      expiration: 3600 # 1 hour for dev
  cache:
    ttl: 60 # 1 minute for dev testing
  mock:
    enabled: true
    delay: 100 # milliseconds
    
management:
  endpoints:
    web:
      exposure:
        include: "*" # expose all endpoints in dev
  endpoint:
    health:
      show-details: always