audify:
  jwt:
    secret: ${AUDIFY_JWT_SECRET:audify-local-secret-key-for-testing-only-minimum-256-bits}
    expiration: ${AUDIFY_JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  async-gateway:
    base-url: http://localhost:8080
    connect-timeout-millis: 1000
    read-timeout-millis: 2500
    request-timeout-millis: 2500
spring:
  datasource:
    url: jdbc:h2:mem:audify_local;MODE=MSSQLServer;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true        # Enable web console for inspecting in-memory DB
      path: /h2-console    # Access at http://localhost:8080/h2-console
      settings:
        web-allow-others: false  # Limit to localhost
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Auto-create tables from @Entity classes on startup, drop on shutdown
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  flyway:
    enabled: false  # Disabled for PoC - using Hibernate auto-create instead

logging:
  level:
    root: INFO
    com.audify: DEBUG

# SpringDoc OpenAPI / Swagger UI Configuration
springdoc:
  api-docs:
    path: /api-docs          # OpenAPI JSON at http://localhost:8080/api-docs
  swagger-ui:
    path: /swagger-ui.html   # Swagger UI at http://localhost:8080/swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
